/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root'
import { Route as newRouteImport } from './routes/new'
import { Route as serverRouteImport } from './routes/_server'
import { Route as viewRouteImport } from './routes/view'
import { Route as indexRouteImport } from './routes/index'
import { Route as serverTermsRouteImport } from './routes/_server/terms'
import { Route as serverAboutRouteImport } from './routes/_server/about'

const newRoute = newRouteImport.update({
  id: '/nouveau-lien',
  path: '/nouveau-lien',
  getParentRoute: () => rootRouteImport,
} as any)
const serverRoute = serverRouteImport.update({
  id: '/_server',
  getParentRoute: () => rootRouteImport,
} as any)
const viewRoute = viewRouteImport.update({
  id: '/$shareId',
  path: '/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const serverTermsRoute = serverTermsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => serverRoute,
} as any)
const serverAboutRoute = serverAboutRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => serverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/$shareId': typeof viewRoute
  '/nouveau-lien': typeof newRoute
  '/a-propos': typeof serverAboutRoute
  '/conditions': typeof serverTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/$shareId': typeof viewRoute
  '/nouveau-lien': typeof newRoute
  '/a-propos': typeof serverAboutRoute
  '/conditions': typeof serverTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/$shareId': typeof viewRoute
  '/_server': typeof serverRouteWithChildren
  '/nouveau-lien': typeof newRoute
  '/_server/a-propos': typeof serverAboutRoute
  '/_server/conditions': typeof serverTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shareId' | '/nouveau-lien' | '/a-propos' | '/conditions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shareId' | '/nouveau-lien' | '/a-propos' | '/conditions'
  id:
    | '__root__'
    | '/'
    | '/$shareId'
    | '/_server'
    | '/nouveau-lien'
    | '/_server/a-propos'
    | '/_server/conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  viewRoute: typeof viewRoute
  serverRoute: typeof serverRouteWithChildren
  newRoute: typeof newRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nouveau-lien': {
      id: '/nouveau-lien'
      path: '/nouveau-lien'
      fullPath: '/nouveau-lien'
      preLoaderRoute: typeof newRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_server': {
      id: '/_server'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof serverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shareId': {
      id: '/$shareId'
      path: '/$shareId'
      fullPath: '/$shareId'
      preLoaderRoute: typeof viewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_server/conditions': {
      id: '/_server/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof serverTermsRouteImport
      parentRoute: typeof serverRoute
    }
    '/_server/a-propos': {
      id: '/_server/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof serverAboutRouteImport
      parentRoute: typeof serverRoute
    }
  }
}

interface serverRouteChildren {
  serverAboutRoute: typeof serverAboutRoute
  serverTermsRoute: typeof serverTermsRoute
}

const serverRouteChildren: serverRouteChildren = {
  serverAboutRoute: serverAboutRoute,
  serverTermsRoute: serverTermsRoute,
}

const serverRouteWithChildren =
  serverRoute._addFileChildren(serverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  viewRoute: viewRoute,
  serverRoute: serverRouteWithChildren,
  newRoute: newRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
